Repository Microsoft/containers-rest-cosmos-appservice-java, pull requests merged in 2019-01, with the labels that each got.

#63 Dockerfile multi stage
  api/Dockerfile
  api/azure-pipelines.yml
Labels: enhancement

#67 Update package.json, package-lock.json (Fix for CVE-2018-14732)
  ui/package-lock.json
  ui/package.json
Labels: User Interface, bug

#66 Minor edit to the bug-template.
  .github/ISSUE_TEMPLATE/1-bug_report.md
Labels: enhancement

#68 CORS Bug in App Settings
  api/README.md
  docs/buildAndReleasePipelines.md
  infrastructure/azuredeploy.json
Labels: Documentation, Infrastructure, bug

#70 Adding local development files.
  api/.env
  api/Dockerfile-development
Labels: API, enhancement

#72 Change related to selecting app service plan type for dev and non-dev environments
  infrastructure/azure-pipelines.yml
  infrastructure/azuredeploy.json
Labels: enhancement

#76 Moving load_env to data dir...
  data/load_env.sh
Labels: Infrastructure

#74 Fixed Unique Id and reordered concatenation.
  infrastructure/global-resources/azuredeploy.json
Labels: Infrastructure, bug

#82 Update documentation for global resources deployment
  infrastructure/azuredeploy.json
  infrastructure/global-resources/README.md
  infrastructure/global-resources/azuredeploy.json
Labels: Documentation, enhancement

#86 Fix issue with boolean parameter(dev_env) in the ARM template
  infrastructure/azuredeploy.json
Labels: bug
